"""
gen_notebook.py  —  Generates mmlongbench_e2e.ipynb
Run from the mmlongbench_baseline/ directory:
    python gen_notebook.py
"""
import json, pathlib, uuid

def cell_id():
    return uuid.uuid4().hex[:8]

def md(source):
    return {"cell_type": "markdown", "id": cell_id(), "metadata": {}, "source": source}

def code(source):
    return {
        "cell_type": "code", "execution_count": None,
        "id": cell_id(), "metadata": {}, "outputs": [],
        "source": source,
    }

cells = []

# ── Phase 0 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "# GraMM-RAG — MMLongBench-Doc End-to-End Implementation\n"
    "\n"
    "**Full end-to-end notebook** for the dissertation.  \n"
    "Dataset: `yubo2333/MMLongBench-Doc` — 1,091 QA records, 135 PDFs, avg 47.5 pages.  \n"
    "Generation model: **Qwen2.5-VL-72B-Instruct** (Together.ai).  \n"
    "Metric: **F1** (token overlap with gold answer) + ANLS + Accuracy.\n"
    "\n"
    "| Phase | Description |\n"
    "|---|---|\n"
    "| 0 | Setup & configuration |\n"
    "| 1 | Load all 1,091 QA records + EDA |\n"
    "| 1.5 | Exploratory data analysis — corpus stats, charts, tables |\n"
    "| 2 | Verify PDF availability from local folder |\n"
    "| 3 | Parse PDFs with MinerU + temporal annotation |\n"
    "| 4 | Compute embeddings (E5-Mistral-7B + SigLIP) + build PyG graphs |\n"
    "| 5 | Train HGT with evidence-guided InfoNCE loss (50 epochs) |\n"
    "| 6 | Train query router (DeBERTa-v3-base, 3 epochs) |\n"
    "| 7 | Tune reward function (α, β, λ, τ grid search) |\n"
    "| 8 | Flat-vector RAG baseline (FAISS + Qwen2.5-VL-72B) |\n"
    "| 9 | GraMM-RAG full evaluation (3 seeds × 1,091 questions) |\n"
    "| 10 | Results comparison table |\n"
    "\n"
    "**Prerequisites:** GPU with ≥16 GB VRAM, `TOGETHER_API_KEY`, `OPENAI_API_KEY`, PDFs in `data/mmlongbench/pdfs/`."
))

cells.append(code(
    "# ═══════════════════════════════════════════════════════════════════════════\n"
    "# PHASE 0 — Setup & Configuration\n"
    "# ═══════════════════════════════════════════════════════════════════════════\n"
    "\n"
    "N_PILOT = None     # set an int (e.g. 100) for a quick pilot run\n"
    "\n"
    "SEED          = 42\n"
    "HF_REPO       = 'yubo2333/MMLongBench-Doc'\n"
    "HGT_EPOCHS    = 50\n"
    "ROUTER_EPOCHS = 3\n"
    "\n"
    "import sys, pathlib\n"
    "ROOT = pathlib.Path('.').resolve()   # repo root (src/ lives here)\n"
    "sys.path.insert(0, str(ROOT))\n"
    "\n"
    "DATA_DIR    = ROOT / 'data'        / 'mmlongbench'\n"
    "PDF_DIR     = DATA_DIR / 'pdfs'\n"
    "PARSED_DIR  = ROOT / 'parsed'     / 'mmlongbench'\n"
    "EMB_DIR     = ROOT / 'embeddings' / 'mmlongbench'\n"
    "GRAPH_DIR   = ROOT / 'graphs'     / 'mmlongbench'\n"
    "MODEL_DIR   = ROOT / 'results'    / 'models'\n"
    "RESULTS_DIR = ROOT / 'results'\n"
    "\n"
    "# ─── Fallback path variables (defined early so later phases never NameError)\n"
    "hgt_save_path   = MODEL_DIR / 'hgt_mmlb'  / 'best_model.pt'\n"
    "reward_save     = MODEL_DIR / 'reward_mmlb.json'\n"
    "router_save_dir = MODEL_DIR / 'router_mmlb' / 'best_model'\n"
    "vector_out_path = RESULTS_DIR / 'baseline_vector_mmlb.json'\n"
    "faiss_indices     = {}       # populated in Phase 8\n"
    "gramm_results     = {}       # populated in Phase 9\n"
    "doc_id_to_pdf     = {}       # populated in Phase 2 cell 2\n"
    "parseable_doc_ids = []       # populated in Phase 2 cell 2\n"
    "\n"
    "print(f'ROOT:   {ROOT}')\n"
    "print(f'DEVICE: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"CPU\"}')\n"
    "print(f'N_PILOT = {N_PILOT}  (full 1,091-question run)')"
))

cells.append(code(
    "import json, random, ast, logging, os\n"
    "from pathlib import Path\n"
    "from collections import Counter, defaultdict\n"
    "import torch\n"
    "\n"
    "logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')\n"
    "logger = logging.getLogger('mmlb_e2e')\n"
    "\n"
    "DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
    "print(f'Device: {DEVICE}')\n"
    "\n"
    "os.environ.setdefault('TOGETHER_API_KEY', os.environ.get('TOGETHER_API_KEY', ''))\n"
    "os.environ.setdefault('OPENAI_API_KEY',   os.environ.get('OPENAI_API_KEY',   ''))\n"
    "\n"
    "if not os.environ.get('TOGETHER_API_KEY'):\n"
    "    print('⚠ TOGETHER_API_KEY not set — generation will use extractive fallback')\n"
    "if not os.environ.get('OPENAI_API_KEY'):\n"
    "    print('⚠ OPENAI_API_KEY not set — KG triplets will be empty (safe to proceed)')"
))

cells.append(code(
    "for d in [DATA_DIR, PDF_DIR, PARSED_DIR, EMB_DIR, GRAPH_DIR,\n"
    "          MODEL_DIR / 'hgt_mmlb',\n"
    "          MODEL_DIR / 'router_mmlb',\n"
    "          RESULTS_DIR / 'figures']:\n"
    "    d.mkdir(parents=True, exist_ok=True)\n"
    "print('All directories ready.')"
))

# ── Phase 1 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 1 — Load Data\n"
    "\n"
    "Load all 1,091 MMLongBench-Doc QA records. Normalise string-encoded fields\n"
    "(`evidence_pages`, `evidence_sources`) to Python lists for downstream use.\n"
    "Set `N_PILOT` to an integer (e.g. 100) at the top of Phase 0 for a quick smoke-test."
))

cells.append(code(
    "def parse_str_list(s):\n"
    "    \"\"\"Parse strings like '[5]' or '[19, 20]' to int/str lists.\"\"\"\n"
    "    if not s or s in ('[]', 'None', None):\n"
    "        return []\n"
    "    try:\n"
    "        result = ast.literal_eval(s) if isinstance(s, str) else s\n"
    "        return list(result) if isinstance(result, (list, tuple)) else []\n"
    "    except Exception:\n"
    "        return []\n"
    "\n"
    "all_questions = json.loads((DATA_DIR / 'mmlongbench_doc.json').read_text(encoding='utf-8'))\n"
    "\n"
    "for q in all_questions:\n"
    "    q['_evidence_pages']   = [int(p) for p in parse_str_list(q.get('evidence_pages', '[]'))]\n"
    "    q['_evidence_sources'] = parse_str_list(q.get('evidence_sources', '[]'))\n"
    "    # NOTE: all 1,091 questions have non-null answers. answer_format='None' (22.4%)\n"
    "    # means free-form format, NOT unanswerable.\n"
    "    q['_unanswerable']     = q.get('answer') is None or str(q.get('answer', '')).strip() == ''\n"
    "    q['_freeform_fmt']     = q.get('answer_format') == 'None'   # 22.4% free-form\n"
    "    q['_n_ev_pages']       = len(q['_evidence_pages'])\n"
    "    q['_q_words']          = len(q['question'].split())\n"
    "    q['_a_words']          = len(str(q.get('answer') or '').split())\n"
    "\n"
    "random.seed(SEED)\n"
    "pilot_questions = random.sample(all_questions, N_PILOT) if N_PILOT else all_questions\n"
    "pilot_doc_ids   = sorted({q['doc_id'] for q in pilot_questions})\n"
    "\n"
    "print(f'Total QA records  : {len(all_questions):,}')\n"
    "print(f'Pilot questions   : {len(pilot_questions):,}')\n"
    "print(f'Unique pilot docs : {len(pilot_doc_ids)}')"
))

cells.append(code(
    "import pandas as pd\n"
    "\n"
    "type_counts = Counter(q['doc_type'] for q in pilot_questions)\n"
    "fmt_counts  = Counter(q.get('answer_format', 'Unknown') for q in pilot_questions)\n"
    "n_unanswerable = sum(q['_unanswerable'] for q in pilot_questions)\n"
    "n_crosspage    = sum(q['_n_ev_pages'] > 1 for q in pilot_questions)\n"
    "n_visual = sum(\n"
    "    any(s in ('Chart', 'Figure', 'Table') for s in q['_evidence_sources'])\n"
    "    for q in pilot_questions)\n"
    "\n"
    "print(f'=== Pilot Set Statistics (N={len(pilot_questions)}) ===')\n"
    "print(f'  Unanswerable   : {n_unanswerable} ({100*n_unanswerable/len(pilot_questions):.1f}%)')\n"
    "print(f'  Cross-page     : {n_crosspage} ({100*n_crosspage/len(pilot_questions):.1f}%)')\n"
    "print(f'  Visual evidence: {n_visual} ({100*n_visual/len(pilot_questions):.1f}%)')\n"
    "print()\n"
    "print('Doc types (top 5):', dict(type_counts.most_common(5)))\n"
    "print('Answer formats:', dict(fmt_counts))"
))

# ── Phase 1.5 — Exploratory Data Analysis ────────────────────────────────────
cells.append(md(
    "## Phase 1.5 — Exploratory Data Analysis\n"
    "\n"
    "Comprehensive descriptive statistics, charts, and tables for the full\n"
    "MMLongBench-Doc corpus and the pilot subset.  \n"
    "All figures are saved to `results/figures/`.\n"
    "\n"
    "| Analysis | Description |\n"
    "|---|---|\n"
    "| Corpus overview | Key stats table (full vs pilot) |\n"
    "| Doc type distribution | Bar chart — top document categories |\n"
    "| Answer format distribution | Horizontal bar chart |\n"
    "| Evidence pages distribution | Histogram — pages required per question |\n"
    "| Questions per document | Histogram — workload distribution across PDFs |\n"
    "| Evidence sources | Bar chart — Chart / Table / Figure / Text breakdown |\n"
    "| Question / answer length | Histogram — word counts |\n"
    "| Unanswerable by category | Stacked bar — answerable vs unanswerable by doc_type |\n"
    "| Cross-tabulation | Heatmap — doc_type × answer_format |\n"
    "| Sample QA pairs | Table — 5 example questions per answer format |"
))

cells.append(code(
    "import matplotlib\n"
    "matplotlib.use('Agg')   # non-interactive backend for nbconvert\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.gridspec as gridspec\n"
    "import seaborn as sns\n"
    "import numpy as np\n"
    "\n"
    "sns.set_theme(style='whitegrid', palette='muted')\n"
    "FIG_DIR = RESULTS_DIR / 'figures'\n"
    "FIG_DIR.mkdir(exist_ok=True)\n"
    "\n"
    "# ─── Full corpus derived stats ────────────────────────────────────────────\n"
    "N_ALL   = len(all_questions)\n"
    "N_DOCS  = len({q['doc_id'] for q in all_questions})\n"
    "N_UNANS    = sum(q['_unanswerable']  for q in all_questions)\n"
    "N_FREEFORM = sum(q['_freeform_fmt']  for q in all_questions)\n"
    "N_CROSS    = sum(q['_n_ev_pages'] > 1 for q in all_questions)\n"
    "N_VIS      = sum(\n"
    "    any(s in ('Chart','Figure','Table') for s in q['_evidence_sources'])\n"
    "    for q in all_questions)\n"
    "MEAN_EV = np.mean([q['_n_ev_pages'] for q in all_questions])\n"
    "MEAN_QW = np.mean([q['_q_words']    for q in all_questions])\n"
    "MEAN_AW = np.mean([q['_a_words']    for q in all_questions])\n"
    "\n"
    "p_freeform = sum(q['_freeform_fmt'] for q in pilot_questions)\n"
    "\n"
    "overview = pd.DataFrame({\n"
    "    'Metric': [\n"
    "        'Total QA records', 'Unique PDFs',\n"
    "        'Null/empty answer (truly unanswerable)',\n"
    "        'Free-form format (answer_format=None)',\n"
    "        'Cross-page (>1 evidence page)',\n"
    "        'Visual evidence (Chart/Table/Figure)',\n"
    "        'Mean evidence pages',\n"
    "        'Mean question length (words)',\n"
    "        'Mean answer length (words)',\n"
    "    ],\n"
    "    'Full corpus (1,091)': [\n"
    "        f'{N_ALL:,}', f'{N_DOCS}',\n"
    "        f'{N_UNANS} ({100*N_UNANS/N_ALL:.1f}%)',\n"
    "        f'{N_FREEFORM} ({100*N_FREEFORM/N_ALL:.1f}%)',\n"
    "        f'{N_CROSS} ({100*N_CROSS/N_ALL:.1f}%)',\n"
    "        f'{N_VIS} ({100*N_VIS/N_ALL:.1f}%)',\n"
    "        f'{MEAN_EV:.2f}',\n"
    "        f'{MEAN_QW:.1f}',\n"
    "        f'{MEAN_AW:.1f}',\n"
    "    ],\n"
    "    f'Pilot (N={len(pilot_questions)})': [\n"
    "        f'{len(pilot_questions)}', f'{len(pilot_doc_ids)}',\n"
    "        f'{n_unanswerable} ({100*n_unanswerable/len(pilot_questions):.1f}%)',\n"
    "        f'{p_freeform} ({100*p_freeform/len(pilot_questions):.1f}%)',\n"
    "        f'{n_crosspage} ({100*n_crosspage/len(pilot_questions):.1f}%)',\n"
    "        f'{n_visual} ({100*n_visual/len(pilot_questions):.1f}%)',\n"
    "        f\"{np.mean([q['_n_ev_pages'] for q in pilot_questions]):.2f}\",\n"
    "        f\"{np.mean([q['_q_words'] for q in pilot_questions]):.1f}\",\n"
    "        f\"{np.mean([q['_a_words'] for q in pilot_questions]):.1f}\",\n"
    "    ],\n"
    "})\n"
    "print('=== Corpus Overview ===')\n"
    "print(overview.to_string(index=False))"
))

cells.append(code(
    "# ─── Figure 1: Doc type and answer format distributions ──────────────────\n"
    "all_type_counts = Counter(q['doc_type'] for q in all_questions)\n"
    "all_fmt_counts  = Counter(q.get('answer_format','Unknown') for q in all_questions)\n"
    "\n"
    "# Shorten long doc_type labels\n"
    "def shorten(s, n=30):\n"
    "    return s[:n] + '…' if len(s) > n else s\n"
    "\n"
    "top_types = all_type_counts.most_common(10)\n"
    "type_labels = [shorten(t, 28) for t, _ in top_types]\n"
    "type_vals   = [c for _, c in top_types]\n"
    "\n"
    "fmt_items   = sorted(all_fmt_counts.items(), key=lambda x: -x[1])\n"
    "fmt_labels  = [f for f, _ in fmt_items]\n"
    "fmt_vals    = [c for _, c in fmt_items]\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "fig.suptitle('MMLongBench-Doc — Document & Answer Distributions (full corpus)', fontsize=13)\n"
    "\n"
    "# Doc type bar chart\n"
    "bars = axes[0].barh(type_labels[::-1], type_vals[::-1],\n"
    "                    color=sns.color_palette('muted', len(type_vals)))\n"
    "axes[0].set_xlabel('Number of questions')\n"
    "axes[0].set_title('Top 10 Document Types')\n"
    "for bar, val in zip(bars, type_vals[::-1]):\n"
    "    axes[0].text(bar.get_width() + 2, bar.get_y() + bar.get_height()/2,\n"
    "                 str(val), va='center', fontsize=8)\n"
    "\n"
    "# Answer format horizontal bar\n"
    "colors = sns.color_palette('Set2', len(fmt_labels))\n"
    "axes[1].barh(fmt_labels[::-1], fmt_vals[::-1], color=colors)\n"
    "axes[1].set_xlabel('Number of questions')\n"
    "axes[1].set_title('Answer Format Distribution')\n"
    "for i, (label, val) in enumerate(zip(fmt_labels[::-1], fmt_vals[::-1])):\n"
    "    axes[1].text(val + 2, i, f'{val} ({100*val/N_ALL:.1f}%)', va='center', fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig1_type_format_dist.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig1_type_format_dist.png')"
))

cells.append(code(
    "# ─── Figure 2: Evidence pages and questions-per-doc histograms ───────────\n"
    "ev_page_counts = [q['_n_ev_pages'] for q in all_questions]\n"
    "q_per_doc = Counter(q['doc_id'] for q in all_questions)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\n"
    "fig.suptitle('MMLongBench-Doc — Evidence & Coverage Analysis', fontsize=13)\n"
    "\n"
    "# Evidence pages histogram\n"
    "max_ev = max(ev_page_counts) if ev_page_counts else 5\n"
    "bins_ev = range(0, min(max_ev + 2, 15))\n"
    "axes[0].hist(ev_page_counts, bins=bins_ev, color='steelblue',\n"
    "             edgecolor='white', linewidth=0.8, align='left')\n"
    "axes[0].set_xlabel('Number of evidence pages per question')\n"
    "axes[0].set_ylabel('Number of questions')\n"
    "axes[0].set_title('Evidence Pages Required per Question')\n"
    "axes[0].set_xticks(range(0, min(max_ev + 1, 14)))\n"
    "# Annotate proportions\n"
    "for n_pgs in range(0, min(max_ev + 1, 5)):\n"
    "    cnt = ev_page_counts.count(n_pgs)\n"
    "    if cnt > 0:\n"
    "        axes[0].annotate(f'{100*cnt/N_ALL:.1f}%',\n"
    "                         xy=(n_pgs, cnt), ha='center', va='bottom', fontsize=8)\n"
    "\n"
    "# Questions per document histogram\n"
    "qs_per_doc_vals = list(q_per_doc.values())\n"
    "axes[1].hist(qs_per_doc_vals, bins=20, color='coral', edgecolor='white', linewidth=0.8)\n"
    "axes[1].set_xlabel('Questions per PDF document')\n"
    "axes[1].set_ylabel('Number of documents')\n"
    "axes[1].set_title(f'Questions per Document (N={N_DOCS} PDFs)')\n"
    "axes[1].axvline(np.mean(qs_per_doc_vals), color='navy', linestyle='--',\n"
    "                linewidth=1.5, label=f'Mean = {np.mean(qs_per_doc_vals):.1f}')\n"
    "axes[1].axvline(np.median(qs_per_doc_vals), color='darkred', linestyle=':',\n"
    "                linewidth=1.5, label=f'Median = {np.median(qs_per_doc_vals):.0f}')\n"
    "axes[1].legend(fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig2_evidence_coverage.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig2_evidence_coverage.png')\n"
    "print(f'\\nEvidence pages summary:')\n"
    "print(f'  0 (unanswerable or no annotation): {ev_page_counts.count(0):,}')\n"
    "print(f'  1 (single-page):                   {ev_page_counts.count(1):,}')\n"
    "print(f'  2+ (cross-page):                   {sum(c >= 2 for c in ev_page_counts):,}')\n"
    "print(f'  Max evidence pages:                {max(ev_page_counts)}')\n"
    "print(f'  Mean questions/doc:                {np.mean(qs_per_doc_vals):.1f}')\n"
    "print(f'  Max questions/doc:                 {max(qs_per_doc_vals)}')"
))

cells.append(code(
    "# ─── Figure 3: Evidence sources and question/answer length distributions ──\n"
    "all_sources = [s for q in all_questions for s in q['_evidence_sources']]\n"
    "src_counts  = Counter(all_sources)\n"
    "\n"
    "q_words_all = [q['_q_words'] for q in all_questions]\n"
    "a_words_all = [q['_a_words'] for q in all_questions if not q['_unanswerable']]\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(15, 4.5))\n"
    "fig.suptitle('MMLongBench-Doc — Evidence Sources & Text Length Analysis', fontsize=13)\n"
    "\n"
    "# Evidence sources bar chart\n"
    "src_labels = [k for k, _ in src_counts.most_common()]\n"
    "src_vals   = [v for _, v in src_counts.most_common()]\n"
    "axes[0].bar(src_labels, src_vals,\n"
    "            color=sns.color_palette('Set1', len(src_labels)))\n"
    "axes[0].set_xlabel('Evidence source type')\n"
    "axes[0].set_ylabel('Count (QA × sources)')\n"
    "axes[0].set_title('Evidence Source Types')\n"
    "for i, (lbl, v) in enumerate(zip(src_labels, src_vals)):\n"
    "    axes[0].text(i, v + 2, str(v), ha='center', fontsize=9)\n"
    "\n"
    "# Question word count histogram\n"
    "axes[1].hist(q_words_all, bins=30, color='mediumseagreen', edgecolor='white')\n"
    "axes[1].set_xlabel('Question length (words)')\n"
    "axes[1].set_ylabel('Number of questions')\n"
    "axes[1].set_title(f'Question Length Distribution\\n(mean={np.mean(q_words_all):.1f}, '\n"
    "                  f'median={np.median(q_words_all):.0f})')\n"
    "axes[1].axvline(np.mean(q_words_all), color='red', linestyle='--', linewidth=1.5)\n"
    "\n"
    "# Answer word count histogram (answerable only)\n"
    "axes[2].hist(a_words_all, bins=30, color='mediumpurple', edgecolor='white')\n"
    "axes[2].set_xlabel('Answer length (words)')\n"
    "axes[2].set_ylabel('Number of answers')\n"
    "axes[2].set_title(f'Answer Length Distribution (answerable only)\\n'\n"
    "                  f'(mean={np.mean(a_words_all):.1f}, median={np.median(a_words_all):.0f})')\n"
    "axes[2].axvline(np.mean(a_words_all), color='red', linestyle='--', linewidth=1.5)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig3_sources_length.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig3_sources_length.png')\n"
    "print('\\nEvidence source counts:', dict(src_counts.most_common()))\n"
    "print(f'Questions with no evidence source annotation: '\n"
    "      f\"{sum(len(q['_evidence_sources'])==0 for q in all_questions)}\")"
))

cells.append(code(
    "# ─── Figure 4: Unanswerable rate by doc_type (top categories) ────────────\n"
    "top_doc_types = [t for t, _ in all_type_counts.most_common(8)]\n"
    "unans_by_type = {}\n"
    "for dt in top_doc_types:\n"
    "    qs = [q for q in all_questions if q['doc_type'] == dt]\n"
    "    unans = sum(q['_unanswerable'] for q in qs)\n"
    "    unans_by_type[shorten(dt, 26)] = (unans, len(qs) - unans, len(qs))\n"
    "\n"
    "labels   = list(unans_by_type.keys())\n"
    "unans_v  = [v[0] for v in unans_by_type.values()]\n"
    "ans_v    = [v[1] for v in unans_by_type.values()]\n"
    "totals   = [v[2] for v in unans_by_type.values()]\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(11, 5))\n"
    "x = np.arange(len(labels))\n"
    "width = 0.55\n"
    "b1 = ax.bar(x, ans_v,   width, label='Answerable',   color='steelblue')\n"
    "b2 = ax.bar(x, unans_v, width, bottom=ans_v,\n"
    "            label='Unanswerable', color='salmon')\n"
    "\n"
    "ax.set_xticks(x)\n"
    "ax.set_xticklabels(labels, rotation=28, ha='right', fontsize=9)\n"
    "ax.set_ylabel('Number of questions')\n"
    "ax.set_title('Answerable vs Unanswerable by Document Type (top 8 categories)')\n"
    "ax.legend()\n"
    "\n"
    "for i, (a, u, tot) in enumerate(zip(ans_v, unans_v, totals)):\n"
    "    if u > 0:\n"
    "        ax.text(i, tot + 1, f'{100*u/tot:.0f}%\\nunanswer', ha='center', fontsize=7.5)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig4_unanswerable_by_type.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig4_unanswerable_by_type.png')"
))

cells.append(code(
    "# ─── Figure 5: Cross-tab heatmap — doc_type × answer_format ─────────────\n"
    "top8_types  = [t for t, _ in all_type_counts.most_common(8)]\n"
    "all_formats = sorted({q.get('answer_format','Unknown') for q in all_questions})\n"
    "\n"
    "xtab = pd.crosstab(\n"
    "    pd.Series([shorten(q['doc_type'],26) for q in all_questions], name='doc_type'),\n"
    "    pd.Series([q.get('answer_format','Unknown') for q in all_questions], name='answer_format')\n"
    ")\n"
    "# Keep only top 8 doc types\n"
    "top8_short = [shorten(t,26) for t in top8_types]\n"
    "xtab = xtab.loc[[t for t in top8_short if t in xtab.index]]\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(10, 5))\n"
    "sns.heatmap(xtab, annot=True, fmt='d', cmap='YlOrRd',\n"
    "            linewidths=0.5, ax=ax, cbar_kws={'label': 'Count'})\n"
    "ax.set_title('Cross-tabulation: Document Type × Answer Format (top 8 doc types)')\n"
    "ax.set_xlabel('Answer Format')\n"
    "ax.set_ylabel('Document Type')\n"
    "plt.xticks(rotation=30, ha='right')\n"
    "plt.yticks(rotation=0)\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig5_crosstab_heatmap.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig5_crosstab_heatmap.png')\n"
    "print('\\n=== Cross-tabulation: doc_type × answer_format ===')\n"
    "print(xtab.to_string())"
))

cells.append(code(
    "# ─── Figure 6: Evidence page number distribution (which pages cited most) ─\n"
    "all_ev_page_nums = [p for q in all_questions for p in q['_evidence_pages']]\n"
    "page_counter = Counter(all_ev_page_nums)\n"
    "top_pages = page_counter.most_common(30)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4.5))\n"
    "fig.suptitle('MMLongBench-Doc — Evidence Page Analysis', fontsize=13)\n"
    "\n"
    "# Top 30 most cited page numbers\n"
    "pg_nums = [p for p, _ in top_pages]\n"
    "pg_vals = [v for _, v in top_pages]\n"
    "axes[0].bar(range(len(pg_nums)), pg_vals, color='teal', edgecolor='white')\n"
    "axes[0].set_xticks(range(len(pg_nums)))\n"
    "axes[0].set_xticklabels([str(p) for p in pg_nums], rotation=60, fontsize=8)\n"
    "axes[0].set_xlabel('Page number')\n"
    "axes[0].set_ylabel('Citation count')\n"
    "axes[0].set_title('Top 30 Most Cited Evidence Page Numbers')\n"
    "\n"
    "# Cumulative distribution: how many questions need at most k pages\n"
    "ev_counts_sorted = sorted(ev_page_counts)\n"
    "cumulative = np.cumsum([1 for _ in ev_counts_sorted]) / N_ALL * 100\n"
    "axes[1].plot(ev_counts_sorted, cumulative, color='darkblue', linewidth=2)\n"
    "axes[1].fill_between(ev_counts_sorted, cumulative, alpha=0.15, color='blue')\n"
    "axes[1].set_xlabel('Number of evidence pages')\n"
    "axes[1].set_ylabel('Cumulative % of questions')\n"
    "axes[1].set_title('Cumulative Distribution of Evidence Page Count')\n"
    "axes[1].set_ylim(0, 102)\n"
    "# Mark key thresholds\n"
    "for threshold in [1, 2, 3]:\n"
    "    pct = sum(c <= threshold for c in ev_page_counts) / N_ALL * 100\n"
    "    axes[1].axvline(threshold, color='red', linestyle='--', alpha=0.5, linewidth=1)\n"
    "    axes[1].text(threshold + 0.05, pct - 5, f'≤{threshold}pg:\\n{pct:.1f}%',\n"
    "                 fontsize=8, color='darkred')\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig6_evidence_page_dist.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig6_evidence_page_dist.png')\n"
    "print(f'\\nTop 10 most cited page numbers: {top_pages[:10]}')"
))

cells.append(code(
    "# ─── Figure 7: Pilot vs full corpus comparison ────────────────────────────\n"
    "metrics_compare = {\n"
    "    'Free-form fmt (%)': [\n"
    "        100*N_FREEFORM/N_ALL,\n"
    "        100*p_freeform/len(pilot_questions)\n"
    "    ],\n"
    "    'Cross-page (%)': [\n"
    "        100*N_CROSS/N_ALL,\n"
    "        100*n_crosspage/len(pilot_questions)\n"
    "    ],\n"
    "    'Visual evidence (%)': [\n"
    "        100*N_VIS/N_ALL,\n"
    "        100*n_visual/len(pilot_questions)\n"
    "    ],\n"
    "    'Mean evidence pages': [\n"
    "        MEAN_EV,\n"
    "        np.mean([q['_n_ev_pages'] for q in pilot_questions])\n"
    "    ],\n"
    "    'Mean Q length (words)': [\n"
    "        MEAN_QW,\n"
    "        np.mean([q['_q_words'] for q in pilot_questions])\n"
    "    ],\n"
    "}\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(11, 4.5))\n"
    "met_names = list(metrics_compare.keys())\n"
    "full_vals  = [metrics_compare[m][0] for m in met_names]\n"
    "pilot_vals = [metrics_compare[m][1] for m in met_names]\n"
    "\n"
    "x = np.arange(len(met_names))\n"
    "w = 0.35\n"
    "ax.bar(x - w/2, full_vals,  w, label='Full corpus (1,091)', color='steelblue')\n"
    "ax.bar(x + w/2, pilot_vals, w, label=f'Pilot (N={len(pilot_questions)})', color='coral')\n"
    "\n"
    "ax.set_xticks(x)\n"
    "ax.set_xticklabels(met_names, rotation=20, ha='right')\n"
    "ax.set_ylabel('Value')\n"
    "ax.set_title('Pilot vs Full Corpus: Key Characteristics Comparison')\n"
    "ax.legend()\n"
    "\n"
    "for xi, (fv, pv) in enumerate(zip(full_vals, pilot_vals)):\n"
    "    ax.text(xi - w/2, fv + 0.3, f'{fv:.1f}', ha='center', fontsize=8)\n"
    "    ax.text(xi + w/2, pv + 0.3, f'{pv:.1f}', ha='center', fontsize=8)\n"
    "\n"
    "plt.tight_layout()\n"
    "fig.savefig(str(FIG_DIR / 'fig7_pilot_vs_full.png'), dpi=150, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Saved: {FIG_DIR}/fig7_pilot_vs_full.png')"
))

cells.append(code(
    "# ─── Table: Sample QA pairs (5 per answer format) ────────────────────────\n"
    "print('=== Sample QA Pairs by Answer Format ===')\n"
    "for fmt in sorted({q.get('answer_format','Unknown') for q in all_questions}):\n"
    "    sample_qs = [q for q in all_questions\n"
    "                 if q.get('answer_format') == fmt and not q['_unanswerable']]\n"
    "    if not sample_qs:\n"
    "        continue\n"
    "    random.seed(SEED)\n"
    "    sample = random.sample(sample_qs, min(3, len(sample_qs)))\n"
    "    print(f'\\n--- Format: {fmt} ({len(sample_qs)} questions) ---')\n"
    "    rows = []\n"
    "    for q in sample:\n"
    "        rows.append({\n"
    "            'Question': q['question'][:80] + ('…' if len(q['question'])>80 else ''),\n"
    "            'Answer': str(q['answer'])[:50] + ('…' if len(str(q['answer']))>50 else ''),\n"
    "            'Ev. pages': str(q['_evidence_pages']),\n"
    "            'Sources': str(q['_evidence_sources']),\n"
    "        })\n"
    "    print(pd.DataFrame(rows).to_string(index=False))\n"
    "\n"
    "print('\\n=== EDA complete. Figures saved to results/figures/ ===')"
))

# ── Phase 2 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 2 — Verify PDF Availability\n"
    "\n"
    "Reads PDFs from `data/mmlongbench/pdfs/` (flat) and the nested `hf_raw/documents/` subfolder.  \n"
    "Expected: 134–135 PDFs total (one file has a very long filename and may be absent — safe to continue).  \n"
    "If running inside Docker, PDFs are pre-mounted at the path above."
))

cells.append(code(
    "import shutil\n"
    "\n"
    "hf_raw_dir    = PDF_DIR / 'hf_raw'\n"
    "existing_pdfs = list(PDF_DIR.glob('*.pdf'))\n"
    "hf_pdfs       = list(hf_raw_dir.rglob('*.pdf')) if hf_raw_dir.exists() else []\n"
    "\n"
    "print(f'PDFs in flat dir ({PDF_DIR.name}/):  {len(existing_pdfs)}')\n"
    "print(f'PDFs in hf_raw/**:                  {len(hf_pdfs)}')\n"
    "print(f'Total sources:                      {len(existing_pdfs) + len(hf_pdfs)}')\n"
    "\n"
    "if not existing_pdfs and not hf_pdfs:\n"
    "    print()\n"
    "    print('WARNING: No PDFs found in either location.')\n"
    "    print(f'  Expected flat dir: {PDF_DIR}')\n"
    "    print(f'  Expected nested:   {hf_raw_dir}')\n"
    "    print('Phases 3-9 will produce no output without PDFs.')\n"
    "else:\n"
    "    print('PDF sources ready.')"
))

cells.append(code(
    "doc_id_to_pdf = {}\n"
    "\n"
    "for p in PDF_DIR.glob('*.pdf'):\n"
    "    doc_id_to_pdf[p.name] = p\n"
    "\n"
    "if hf_raw_dir.exists():\n"
    "    for p in hf_raw_dir.rglob('*.pdf'):\n"
    "        fname = p.name\n"
    "        if fname not in doc_id_to_pdf:\n"
    "            dest = PDF_DIR / fname\n"
    "            if not dest.exists():\n"
    "                try:\n"
    "                    shutil.copy2(str(p), str(dest))\n"
    "                except Exception as _cp_err:\n"
    "                    logger.warning(f'copy2 failed for {p.name}: {_cp_err}')\n"
    "                    continue\n"
    "            doc_id_to_pdf[fname] = dest\n"
    "\n"
    "all_doc_ids = {q['doc_id'] for q in all_questions}\n"
    "found_all   = {d for d in all_doc_ids if d in doc_id_to_pdf}\n"
    "missing     = all_doc_ids - found_all\n"
    "\n"
    "print(f'PDFs found (unique): {len(doc_id_to_pdf)}')\n"
    "print(f'Docs with PDFs     : {len(found_all)}/{len(all_doc_ids)}')\n"
    "if missing:\n"
    "    print(f'Missing ({len(missing)}): {sorted(missing)[:5]}{\" ...\" if len(missing)>5 else \"\"}')\n"
    "\n"
    "parseable_doc_ids = [d for d in pilot_doc_ids if d in doc_id_to_pdf]\n"
    "print(f'Parseable docs: {len(parseable_doc_ids)}')"
))

# ── Phase 3 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 3 — Parse PDFs with MinerU + Temporal Annotation\n"
    "\n"
    "MinerU (`magic-pdf`) converts each PDF into a structured JSON with:\n"
    "bounding boxes, element types (text/table/figure/equation/section), reading order.\n"
    "\n"
    "Install if needed: `pip install magic-pdf[full]`  \n"
    "**Runtime:** ~30 s/doc × 12–20 pilot docs ≈ 10 min."
))

cells.append(code(
    "from src.parsing.mineru_wrapper import parse_pdf\n"
    "\n"
    "def parse_pilot_docs(parseable_doc_ids, doc_id_to_pdf, PARSED_DIR, PDF_DIR):\n"
    "    parsed_count = skip_count = fail_count = 0\n"
    "    for i, doc_id in enumerate(parseable_doc_ids, 1):\n"
    "        out_path = PARSED_DIR / f'{doc_id}.json'\n"
    "        if out_path.exists():\n"
    "            skip_count += 1\n"
    "            continue\n"
    "        pdf_path = doc_id_to_pdf.get(doc_id)\n"
    "        if not pdf_path or not Path(pdf_path).exists():\n"
    "            logger.warning(f'[{i}] PDF not found: {doc_id}')\n"
    "            fail_count += 1\n"
    "            continue\n"
    "        logger.info(f'[{i}/{len(parseable_doc_ids)}] Parsing: {doc_id}')\n"
    "        try:\n"
    "            art_dir = PARSED_DIR / 'artifacts' / Path(doc_id).stem\n"
    "            result  = parse_pdf(str(pdf_path), str(art_dir))\n"
    "            result.setdefault('doc_id', Path(doc_id).stem)\n"
    "            out_path.write_text(json.dumps(result, indent=2), encoding='utf-8')\n"
    "            parsed_count += 1\n"
    "        except ImportError as e:\n"
    "            print(f'⚠ MinerU not installed: {e}\\n  pip install magic-pdf[full]')\n"
    "            break\n"
    "        except Exception as e:\n"
    "            logger.error(f'Parse failed {doc_id}: {e}')\n"
    "            fail_count += 1\n"
    "    return parsed_count, skip_count, fail_count\n"
    "\n"
    "parsed_count, skip_count, fail_count = parse_pilot_docs(\n"
    "    parseable_doc_ids, doc_id_to_pdf, PARSED_DIR, PDF_DIR\n"
    ")\n"
    "print(f'Parsed: {parsed_count}, Skipped (cached): {skip_count}, Failed: {fail_count}')\n"
    "\n"
    "parsed_ids = {p.stem for p in PARSED_DIR.glob('*.json') if p.stem != 'artifacts'}\n"
    "print(f'Total parsed docs available: {len(parsed_ids)}')"
))

cells.append(code(
    "from src.parsing.temporal import annotate_parsed_elements\n"
    "\n"
    "annotated = 0\n"
    "for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "    if pf.stem == 'artifacts':\n"
    "        continue\n"
    "    try:\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "        if any('temporal_markers' in e for e in parsed.get('elements', [])):\n"
    "            continue\n"
    "        parsed = annotate_parsed_elements(parsed, None, use_llm=False)\n"
    "        pf.write_text(json.dumps(parsed, indent=2), encoding='utf-8')\n"
    "        annotated += 1\n"
    "    except Exception as e:\n"
    "        logger.warning(f'Temporal annotation failed {pf.name}: {e}')\n"
    "\n"
    "print(f'Temporal annotation: {annotated} docs annotated')"
))

# ── Phase 4 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 4 — Node Embeddings + PyG Graph Construction\n"
    "\n"
    "**Text nodes:** E5-Mistral-7B-Instruct (4-bit, ~4 GB VRAM) → 256-dim projection.  \n"
    "**Image nodes:** SigLIP-SO400M (~1.5 GB VRAM) → 256-dim projection.  \n"
    "Both run sequentially to stay within 8 GB VRAM.\n"
    "\n"
    "**KG triplets:** GPT-4o-mini extraction (skipped if `OPENAI_API_KEY` not set).  \n"
    "**Runtime:** ~2 min/doc × 12–20 docs."
))

cells.append(code(
    "from src.graph.embeddings import compute_and_save_embeddings\n"
    "\n"
    "embedded_count = skip_emb_count = 0\n"
    "\n"
    "for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "    if pf.stem == 'artifacts':\n"
    "        continue\n"
    "    doc_id = pf.stem\n"
    "    text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "    img_pt  = EMB_DIR / f'{doc_id}_img.pt'\n"
    "    if text_pt.exists() and img_pt.exists():\n"
    "        skip_emb_count += 1\n"
    "        continue\n"
    "    try:\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "        compute_and_save_embeddings(\n"
    "            parsed,\n"
    "            embeddings_dir=str(EMB_DIR),\n"
    "            image_root=str(PDF_DIR / 'artifacts' / doc_id),\n"
    "            device=DEVICE,\n"
    "            text_batch_size=16,\n"
    "            image_batch_size=8,\n"
    "        )\n"
    "        embedded_count += 1\n"
    "    except Exception as e:\n"
    "        logger.error(f'Embedding failed {doc_id}: {e}')\n"
    "\n"
    "print(f'Embeddings computed: {embedded_count}, Skipped (cached): {skip_emb_count}')"
))

cells.append(code(
    "from src.graph.edges import extract_all_triplets\n"
    "from src.graph.builder import build_graph, save_graph\n"
    "\n"
    "openai_client_kg = None\n"
    "if os.environ.get('OPENAI_API_KEY'):\n"
    "    try:\n"
    "        import openai\n"
    "        openai_client_kg = openai.OpenAI(api_key=os.environ['OPENAI_API_KEY'])\n"
    "        print('OpenAI client ready for KG extraction')\n"
    "    except ImportError:\n"
    "        print('openai package not found — KG triplets empty')\n"
    "else:\n"
    "    print('No OPENAI_API_KEY — KG triplets empty (graph still built)')\n"
    "\n"
    "graph_count = skip_graph = 0\n"
    "\n"
    "for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "    if pf.stem == 'artifacts':\n"
    "        continue\n"
    "    doc_id = pf.stem\n"
    "    if (GRAPH_DIR / f'{doc_id}.pt').exists():\n"
    "        skip_graph += 1\n"
    "        continue\n"
    "    text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "    img_pt  = EMB_DIR / f'{doc_id}_img.pt'\n"
    "    if not (text_pt.exists() and img_pt.exists()):\n"
    "        logger.warning(f'Embeddings missing for {doc_id}')\n"
    "        continue\n"
    "    try:\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "        parsed.setdefault('doc_id', doc_id)\n"
    "        embeddings = {\n"
    "            'text': torch.load(text_pt, weights_only=True),\n"
    "            'img':  torch.load(img_pt,  weights_only=True),\n"
    "        }\n"
    "        triplets = []\n"
    "        if openai_client_kg:\n"
    "            try:\n"
    "                triplets = extract_all_triplets(parsed, openai_client_kg)\n"
    "            except Exception as e:\n"
    "                logger.warning(f'KG extraction failed {doc_id}: {e}')\n"
    "        graph = build_graph(doc_id, parsed, embeddings, triplets)\n"
    "        save_graph(graph, str(GRAPH_DIR), doc_id)\n"
    "        graph_count += 1\n"
    "    except Exception as e:\n"
    "        logger.error(f'Graph build failed {doc_id}: {e}')\n"
    "\n"
    "print(f'Graphs built: {graph_count}, Skipped (cached): {skip_graph}')\n"
    "print(f'Total graphs available: {len(list(GRAPH_DIR.glob(\"*.pt\")))}')"
))

# ── Phase 5 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 5 — Train HGT with Evidence-Guided InfoNCE Loss\n"
    "\n"
    "Uses MMLongBench `evidence_pages` annotations to create supervised training triples:\n"
    "- **Anchor:** mean of text node embeddings (query proxy)\n"
    "- **Positive:** nodes on annotated evidence pages\n"
    "- **Negatives:** 15 random non-evidence nodes\n"
    "\n"
    "Saved to `results/models/hgt_mmlb/best_model.pt`."
))

cells.append(code(
    "from src.retrieval.hgt_model import DocumentHGT, info_nce_loss, METADATA\n"
    "from src.graph.builder import load_graph\n"
    "\n"
    "def get_evidence_node_indices(parsed, evidence_pages_set, node_type):\n"
    "    typed = [e for e in parsed['elements'] if e['type'] == node_type]\n"
    "    return [i for i, e in enumerate(typed)\n"
    "            if e.get('page_no', -1) in evidence_pages_set]\n"
    "\n"
    "def build_hgt_triple(item, model, GRAPH_DIR, PARSED_DIR, device):\n"
    "    doc_id   = Path(item['doc_id']).stem\n"
    "    ev_pages = set(item['_evidence_pages'])\n"
    "    graph    = load_graph(str(GRAPH_DIR), doc_id)\n"
    "    if graph is None:\n"
    "        return None\n"
    "    pf = PARSED_DIR / f'{doc_id}.json'\n"
    "    if not pf.exists():\n"
    "        return None\n"
    "    parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "\n"
    "    x_dict = {nt: graph[nt].x.to(device)\n"
    "              for nt in graph.node_types\n"
    "              if hasattr(graph[nt], 'x') and graph[nt].x.shape[0] > 0}\n"
    "    edge_index_dict = {et: graph[et].edge_index.to(device)\n"
    "                       for et in graph.edge_types\n"
    "                       if graph[et].edge_index.shape[1] > 0}\n"
    "    if not x_dict:\n"
    "        return None\n"
    "\n"
    "    out_dict = model(x_dict, edge_index_dict)\n"
    "    text_out = out_dict.get('text')\n"
    "    if text_out is None or text_out.shape[0] == 0:\n"
    "        return None\n"
    "    q_emb = torch.nn.functional.normalize(text_out.mean(0), dim=-1)\n"
    "\n"
    "    pos_embs = []\n"
    "    for nt, embs in out_dict.items():\n"
    "        for idx in get_evidence_node_indices(parsed, ev_pages, nt):\n"
    "            if idx < embs.shape[0]:\n"
    "                pos_embs.append(torch.nn.functional.normalize(embs[idx], dim=-1))\n"
    "\n"
    "    all_embs = torch.cat([e for e in out_dict.values() if e.shape[0] > 0])\n"
    "    if all_embs.shape[0] < 2:\n"
    "        return None\n"
    "    if not pos_embs:\n"
    "        pos_emb = torch.nn.functional.normalize(\n"
    "            all_embs[random.randint(0, all_embs.shape[0]-1)], dim=-1)\n"
    "    else:\n"
    "        pos_emb = random.choice(pos_embs)\n"
    "\n"
    "    n_neg  = min(15, all_embs.shape[0] - 1)\n"
    "    perm   = torch.randperm(all_embs.shape[0])[:n_neg]\n"
    "    neg_embs = torch.nn.functional.normalize(all_embs[perm], dim=-1)\n"
    "    return q_emb, pos_emb, neg_embs\n"
    "\n"
    "print('HGT training helpers defined.')"
))

cells.append(code(
    "random.seed(SEED)\n"
    "torch.manual_seed(SEED)\n"
    "\n"
    "available_graph_ids = [\n"
    "    p.stem for p in GRAPH_DIR.glob('*.pt')\n"
    "    if p.stem in {Path(d).stem for d in pilot_doc_ids}\n"
    "]\n"
    "\n"
    "doc_to_questions = defaultdict(list)\n"
    "for q in pilot_questions:\n"
    "    stem = Path(q['doc_id']).stem\n"
    "    if stem in set(available_graph_ids):\n"
    "        doc_to_questions[stem].append(q)\n"
    "\n"
    "print(f'HGT_EPOCHS = {HGT_EPOCHS}')\n"
    "print(f'Training graphs available: {len(available_graph_ids)}')\n"
    "print(f'Docs with evidence triples: {len(doc_to_questions)}')\n"
    "\n"
    "if hgt_save_path.exists():\n"
    "    print(f'HGT already trained: {hgt_save_path}')\n"
    "elif not available_graph_ids:\n"
    "    print('No graphs available. Run Phase 4 first to build graphs.')\n"
    "else:\n"
    "    hgt_model = DocumentHGT(metadata=METADATA).to(DEVICE)\n"
    "    optimizer = torch.optim.Adam(hgt_model.parameters(), lr=1e-3, weight_decay=1e-4)\n"
    "    best_loss = float('inf')\n"
    "\n"
    "    for epoch in range(HGT_EPOCHS):\n"
    "        hgt_model.train()\n"
    "        total_loss = n_batches = 0\n"
    "        all_qs = [q for qs in doc_to_questions.values() for q in qs]\n"
    "        random.shuffle(all_qs)\n"
    "        for item in all_qs:\n"
    "            triple = build_hgt_triple(item, hgt_model, GRAPH_DIR, PARSED_DIR, DEVICE)\n"
    "            if triple is None:\n"
    "                continue\n"
    "            q_emb, pos_emb, neg_embs = triple\n"
    "            optimizer.zero_grad()\n"
    "            loss = info_nce_loss(q_emb, pos_emb, neg_embs)\n"
    "            if not (torch.isnan(loss) or torch.isinf(loss)):\n"
    "                loss.backward()\n"
    "                optimizer.step()\n"
    "                total_loss += loss.item()\n"
    "                n_batches  += 1\n"
    "        avg_loss = total_loss / max(n_batches, 1)\n"
    "        print(f'Epoch {epoch+1:3d}/{HGT_EPOCHS}  loss={avg_loss:.4f}  batches={n_batches}')\n"
    "        if avg_loss < best_loss:\n"
    "            best_loss = avg_loss\n"
    "            torch.save(hgt_model.state_dict(), hgt_save_path)\n"
    "\n"
    "    print(f'HGT training done. Best loss={best_loss:.4f}  Saved: {hgt_save_path}')"
))

# ── Phase 6 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 6 — Train Query Router (DeBERTa-v3-base)\n"
    "\n"
    "Auto-annotate routing labels from MMLongBench metadata:\n"
    "- **GRAPH** — `evidence_pages` spans > 1 page (cross-page reasoning)\n"
    "- **HYBRID** — single page with visual evidence (Chart / Figure / Table)\n"
    "- **VECTOR** — single page, pure-text factoid\n"
    "\n"
    "Fine-tunes `microsoft/deberta-v3-base`.  \n"
    "Saved to `results/models/router_mmlb/best_model/`."
))

cells.append(code(
    "from src.retrieval.router import build_router_training_data, LABEL2ID\n"
    "\n"
    "all_for_router = []\n"
    "for q in all_questions:\n"
    "    q_copy = dict(q)\n"
    "    q_copy['evidence_pages'] = q['_evidence_pages']  # list, not string\n"
    "    all_for_router.append(q_copy)\n"
    "\n"
    "samples = build_router_training_data(all_for_router, max_samples=len(all_for_router))\n"
    "\n"
    "label_counts = Counter(s['label'] for s in samples)\n"
    "print(f'Router training samples: {len(samples)}')\n"
    "print(f'Label distribution: {dict(label_counts)}')\n"
    "\n"
    "if len(samples) < 30:\n"
    "    print('Augmenting with synthetic samples...')\n"
    "    samples += [\n"
    "        {'query': 'Compare trends across all sections',         'label': 'GRAPH'},\n"
    "        {'query': 'What is the total revenue?',                 'label': 'VECTOR'},\n"
    "        {'query': 'What does the chart on page 5 show?',        'label': 'HYBRID'},\n"
    "        {'query': 'How did costs change over the years?',       'label': 'GRAPH'},\n"
    "        {'query': 'What was net income in 2022?',               'label': 'VECTOR'},\n"
    "        {'query': 'Summarize findings across all figures',      'label': 'GRAPH'},\n"
    "        {'query': 'Which figure shows market share breakdown?', 'label': 'HYBRID'},\n"
    "    ] * 15\n"
    "    print(f'After augmentation: {len(samples)} samples')"
))

cells.append(code(
    "from datasets import Dataset\n"
    "from transformers import (\n"
    "    AutoTokenizer, AutoModelForSequenceClassification,\n"
    "    TrainingArguments, Trainer\n"
    ")\n"
    "import numpy as np\n"
    "\n"
    "if router_save_dir.exists() and any(router_save_dir.iterdir()):\n"
    "    print(f'Router already trained: {router_save_dir}')\n"
    "else:\n"
    "    print(f'ROUTER_EPOCHS = {ROUTER_EPOCHS}')\n"
    "    ds = Dataset.from_dict({\n"
    "        'text':  [s['query'] for s in samples],\n"
    "        'label': [LABEL2ID[s['label']] for s in samples],\n"
    "    })\n"
    "    split    = ds.train_test_split(test_size=0.15, seed=SEED)\n"
    "    train_ds = split['train']\n"
    "    val_ds   = split['test']\n"
    "\n"
    "    model_name = 'microsoft/deberta-v3-base'\n"
    "    tokenizer  = AutoTokenizer.from_pretrained(model_name)\n"
    "\n"
    "    def tokenize(batch):\n"
    "        return tokenizer(batch['text'], truncation=True,\n"
    "                         max_length=128, padding='max_length')\n"
    "\n"
    "    train_enc = train_ds.map(tokenize, batched=True)\n"
    "    val_enc   = val_ds.map(tokenize,   batched=True)\n"
    "\n"
    "    router_model = AutoModelForSequenceClassification.from_pretrained(\n"
    "        model_name, num_labels=3,\n"
    "        id2label={0:'GRAPH',1:'VECTOR',2:'HYBRID'},\n"
    "        label2id={'GRAPH':0,'VECTOR':1,'HYBRID':2},\n"
    "    )\n"
    "\n"
    "    def compute_metrics(eval_pred):\n"
    "        logits, labels = eval_pred\n"
    "        preds = np.argmax(logits, axis=-1)\n"
    "        return {'accuracy': float((preds == labels).mean())}\n"
    "\n"
    "    training_args = TrainingArguments(\n"
    "        output_dir=str(MODEL_DIR / 'router_mmlb'),\n"
    "        num_train_epochs=ROUTER_EPOCHS,\n"
    "        per_device_train_batch_size=8,\n"
    "        per_device_eval_batch_size=8,\n"
    "        learning_rate=2e-5,\n"
    "        weight_decay=0.01,\n"
    "        eval_strategy='epoch',\n"
    "        save_strategy='epoch',\n"
    "        load_best_model_at_end=True,\n"
    "        metric_for_best_model='accuracy',\n"
    "        logging_steps=20,\n"
    "        seed=SEED,\n"
    "        report_to='none',\n"
    "    )\n"
    "    trainer = Trainer(\n"
    "        model=router_model, args=training_args,\n"
    "        train_dataset=train_enc, eval_dataset=val_enc,\n"
    "        compute_metrics=compute_metrics,\n"
    "    )\n"
    "    trainer.train()\n"
    "    trainer.save_model(str(router_save_dir))\n"
    "    tokenizer.save_pretrained(str(router_save_dir))\n"
    "    res = trainer.evaluate()\n"
    "    print(f'Router val accuracy: {res.get(\"eval_accuracy\",0):.4f}')\n"
    "    print(f'Saved: {router_save_dir}')"
))

# ── Phase 7 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 7 — Tune Reward Function (α, β, λ, τ Grid Search)\n"
    "\n"
    "`R(q,K) = α·C + β·S + λ·T`  — C=coverage, S=similarity, T=temporal coherence\n"
    "\n"
    "Grid search on a 20% holdout of pilot questions.  \n"
    "Tuning signal: Spearman correlation between reward score and evidence-page hit."
))

cells.append(code(
    "from src.retrieval.hgt_model import retrieve_top_k\n"
    "from src.retrieval.self_healing import RewardFunction\n"
    "import itertools\n"
    "\n"
    "hgt_model_tune = DocumentHGT(metadata=METADATA).to(DEVICE)\n"
    "if hgt_save_path.exists():\n"
    "    hgt_model_tune.load_state_dict(\n"
    "        torch.load(hgt_save_path, map_location=DEVICE, weights_only=False))\n"
    "    print(f'HGT loaded: {hgt_save_path}')\n"
    "else:\n"
    "    print('HGT not trained yet — using random-init weights for reward tuning')\n"
    "hgt_model_tune.eval()\n"
    "\n"
    "random.seed(SEED + 1)\n"
    "tuning_qs = random.sample(pilot_questions, max(4, int(0.2 * len(pilot_questions))))\n"
    "print(f'Reward tuning on {len(tuning_qs)} held-out questions')\n"
    "\n"
    "grid = [(a, b, l, t)\n"
    "        for a, b, l, t in itertools.product(\n"
    "            [0.30, 0.40, 0.50], [0.30, 0.35, 0.40],\n"
    "            [0.20, 0.25, 0.30], [0.40, 0.50, 0.60, 0.70])\n"
    "        if abs(a + b + l - 1.0) <= 0.05]\n"
    "print(f'Grid size (weight-valid): {len(grid)} configurations')\n"
    "\n"
    "if reward_save.exists():\n"
    "    print(f'Reward params already tuned: {reward_save}')\n"
    "else:\n"
    "    best_score, best_params = -1.0, None\n"
    "    for alpha, beta, lambda_, tau in grid:\n"
    "        rf = RewardFunction(alpha=alpha, beta=beta, lambda_=lambda_, tau=tau)\n"
    "        scores, hits = [], []\n"
    "        for item in tuning_qs:\n"
    "            doc_id = Path(item['doc_id']).stem\n"
    "            graph  = load_graph(str(GRAPH_DIR), doc_id)\n"
    "            pf     = PARSED_DIR / f'{doc_id}.json'\n"
    "            if graph is None or not pf.exists():\n"
    "                continue\n"
    "            parsed = json.loads(pf.read_text(encoding='utf-8'))\n"
    "            with torch.no_grad():\n"
    "                node_emb_dict = hgt_model_tune.encode_nodes(\n"
    "                    {nt: graph[nt].x.to(DEVICE) for nt in graph.node_types\n"
    "                     if hasattr(graph[nt],'x') and graph[nt].x.shape[0]>0},\n"
    "                    {et: graph[et].edge_index.to(DEVICE) for et in graph.edge_types\n"
    "                     if graph[et].edge_index.shape[1]>0},\n"
    "                )\n"
    "            text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "            q_emb = (torch.load(text_pt, weights_only=True).mean(0)\n"
    "                     if text_pt.exists() else torch.zeros(256))\n"
    "            nodes = retrieve_top_k(q_emb, node_emb_dict, top_k=10)\n"
    "            rd = rf.compute(q_emb, nodes, node_emb_dict, parsed, [])\n"
    "            scores.append(rd['reward'])\n"
    "            ev_pages = set(item['_evidence_pages'])\n"
    "            ret_pages = set()\n"
    "            for n in nodes:\n"
    "                typed = [e for e in parsed['elements'] if e['type']==n['node_type']]\n"
    "                if n['local_idx'] < len(typed):\n"
    "                    ret_pages.add(typed[n['local_idx']].get('page_no',-1))\n"
    "            hits.append(1.0 if ev_pages and ev_pages & ret_pages else 0.0)\n"
    "        if len(scores) > 2 and sum(hits) > 0:\n"
    "            from scipy.stats import spearmanr\n"
    "            corr, _ = spearmanr(scores, hits)\n"
    "            corr = 0.0 if corr != corr else float(corr)\n"
    "        else:\n"
    "            corr = 0.0\n"
    "        if corr > best_score:\n"
    "            best_score = corr\n"
    "            best_params = {'alpha':alpha,'beta':beta,'lambda_':lambda_,'tau':tau}\n"
    "\n"
    "    if best_params is None:\n"
    "        best_params = {'alpha':0.40,'beta':0.35,'lambda_':0.25,'tau':0.60}\n"
    "        print('Grid search inconclusive. Using defaults.')\n"
    "    reward_save.write_text(json.dumps(best_params, indent=2))\n"
    "    print(f'Best reward params (corr={best_score:.3f}): {best_params}')\n"
    "\n"
    "print('Reward tuning complete.')"
))

# ── Phase 8 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 8 — Flat-Vector RAG Baseline\n"
    "\n"
    "Baseline: FAISS vector search (no graph, no self-healing) + Qwen2.5-VL-72B.  \n"
    "Uses the same VLM backend as GraMM-RAG to isolate retrieval contribution.\n"
    "\n"
    "Results saved to `results/baseline_vector_mmlb_pilot.json`."
))

cells.append(code(
    "from src.retrieval.vector_retrieval import VectorIndex\n"
    "from src.generation.prompt_builder import build_prompt\n"
    "from src.generation.vlm_client import VLMClient\n"
    "from src.evaluation.metrics import compute_all_metrics\n"
    "\n"
    "faiss_indices = {}\n"
    "\n"
    "for pf in sorted(PARSED_DIR.glob('*.json')):\n"
    "    if pf.stem == 'artifacts':\n"
    "        continue\n"
    "    doc_id     = pf.stem\n"
    "    index_path = EMB_DIR / f'{doc_id}_faiss.index'\n"
    "    text_pt    = EMB_DIR / f'{doc_id}_text.pt'\n"
    "    img_pt     = EMB_DIR / f'{doc_id}_img.pt'\n"
    "\n"
    "    vi = VectorIndex()\n"
    "    if index_path.exists():\n"
    "        try:\n"
    "            vi.load(str(index_path))\n"
    "            faiss_indices[doc_id] = vi\n"
    "            continue\n"
    "        except Exception:\n"
    "            pass\n"
    "\n"
    "    if not text_pt.exists():\n"
    "        continue\n"
    "    try:\n"
    "        parsed   = json.loads(pf.read_text(encoding='utf-8'))\n"
    "        text_emb = torch.load(text_pt, weights_only=True)\n"
    "        img_emb  = (torch.load(img_pt, weights_only=True)\n"
    "                    if img_pt.exists() else torch.zeros(0, 256))\n"
    "        elements = parsed.get('elements', [])\n"
    "        tc = Counter(e['type'] for e in elements)\n"
    "        node_emb_dict = {}\n"
    "        cur = 0\n"
    "        for nt, cnt in [('text',tc.get('text',0)),('section',tc.get('section',0)),\n"
    "                         ('equation',tc.get('equation',0))]:\n"
    "            if cnt > 0 and cur < text_emb.shape[0]:\n"
    "                end = min(cur + cnt, text_emb.shape[0])\n"
    "                node_emb_dict[nt] = text_emb[cur:end]\n"
    "                cur = end\n"
    "        cur = 0\n"
    "        for nt, cnt in [('figure',tc.get('figure',0)),('table',tc.get('table',0))]:\n"
    "            if cnt > 0 and img_emb.shape[0] > 0 and cur < img_emb.shape[0]:\n"
    "                end = min(cur + cnt, img_emb.shape[0])\n"
    "                node_emb_dict[nt] = img_emb[cur:end]\n"
    "                cur = end\n"
    "        if node_emb_dict:\n"
    "            vi.build(node_emb_dict, parsed, doc_id)\n"
    "            if vi.index is not None:\n"
    "                vi.save(str(index_path))\n"
    "                faiss_indices[doc_id] = vi\n"
    "    except Exception as e:\n"
    "        logger.warning(f'FAISS build failed {doc_id}: {e}')\n"
    "\n"
    "print(f'FAISS indices built: {len(faiss_indices)}')"
))

cells.append(code(
    "if vector_out_path.exists():\n"
    "    print(f'Flat-vector RAG results exist: {vector_out_path}')\n"
    "    vector_results = json.loads(vector_out_path.read_text())\n"
    "else:\n"
    "    vlm_vec = VLMClient(provider='together', together_model='Qwen/Qwen2.5-VL-72B-Instruct')\n"
    "    v_preds, v_golds, v_refused = [], [], []\n"
    "\n"
    "    for i, item in enumerate(pilot_questions):\n"
    "        question = item['question']\n"
    "        gold     = item.get('answer', '')\n"
    "        doc_id   = Path(item['doc_id']).stem\n"
    "\n"
    "        text_pt = EMB_DIR / f'{doc_id}_text.pt'\n"
    "        q_emb   = (torch.load(text_pt, weights_only=True).mean(0)\n"
    "                   if text_pt.exists() else torch.zeros(256))\n"
    "\n"
    "        vi    = faiss_indices.get(doc_id)\n"
    "        nodes = vi.search(q_emb, top_k=10) if vi and vi.index else []\n"
    "\n"
    "        pf     = PARSED_DIR / f'{doc_id}.json'\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8')) if pf.exists() else {'elements':[]}\n"
    "\n"
    "        prompt = build_prompt(question, nodes, parsed, {}, False,\n"
    "                              benchmark='mmlongbench')\n"
    "        answer = vlm_vec.generate(prompt, temperature=0.0, max_tokens=256)\n"
    "\n"
    "        v_preds.append(answer)\n"
    "        v_golds.append(str(gold) if gold is not None else '')\n"
    "        v_refused.append(False)\n"
    "\n"
    "        if (i + 1) % 10 == 0:\n"
    "            print(f'  Vector RAG [{i+1}/{len(pilot_questions)}]')\n"
    "\n"
    "    v_metrics = compute_all_metrics(v_preds, v_golds,\n"
    "                                    [True]*len(v_preds), v_refused)\n"
    "    vector_results = {\n"
    "        'system': 'Flat-vector RAG', 'n_questions': len(pilot_questions),\n"
    "        'metrics': v_metrics, 'predictions': v_preds, 'golds': v_golds,\n"
    "    }\n"
    "    vector_out_path.write_text(json.dumps(vector_results, indent=2))\n"
    "    print(f'Flat-vector RAG: ANLS={v_metrics[\"anls\"]:.3f} '\n"
    "          f'F1={v_metrics[\"f1\"]:.3f} Acc={v_metrics[\"accuracy\"]:.3f}')\n"
    "    print(f'Saved: {vector_out_path}')"
))

# ── Phase 9 ───────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 9 — GraMM-RAG Full Evaluation (3 Seeds)\n"
    "\n"
    "Full pipeline: **route → retrieve (HGT/FAISS/hybrid) → self-heal → generate → score**\n"
    "\n"
    "Uses MMLongBench-specific trained models from `results/models/`.  \n"
    "Results saved per seed to `results/gramm_mmlongbench_s{seed}.json`."
))

cells.append(code(
    "from src.retrieval.router import QueryRouter\n"
    "from src.retrieval.self_healing import SelfHealingRetriever\n"
    "\n"
    "hgt_model_eval = DocumentHGT(metadata=METADATA).to(DEVICE)\n"
    "if hgt_save_path.exists():\n"
    "    hgt_model_eval.load_state_dict(\n"
    "        torch.load(hgt_save_path, map_location=DEVICE, weights_only=False))\n"
    "    print(f'HGT loaded: {hgt_save_path}')\n"
    "else:\n"
    "    print('⚠ HGT weights not found — using random init')\n"
    "hgt_model_eval.eval()\n"
    "\n"
    "router = QueryRouter(\n"
    "    model_dir=str(router_save_dir) if router_save_dir.exists() else None,\n"
    "    device=DEVICE,\n"
    ")\n"
    "print(f'Router: {\"DeBERTa\" if router.model else \"heuristic fallback\"}')\n"
    "\n"
    "reward_fn = RewardFunction(\n"
    "    params_path=str(reward_save) if reward_save.exists() else None)\n"
    "\n"
    "retriever = SelfHealingRetriever(\n"
    "    hgt_model=hgt_model_eval, reward_fn=reward_fn,\n"
    "    top_k=10, expansion_k=5, max_rounds=2,\n"
    ")\n"
    "vlm_eval = VLMClient(provider='together', together_model='Qwen/Qwen2.5-VL-72B-Instruct')\n"
    "print('All GraMM-RAG components loaded.')"
))

cells.append(code(
    "def run_gramm_rag_mmlb(questions, seed):\n"
    "    random.seed(seed)\n"
    "    torch.manual_seed(seed)\n"
    "    predictions, golds, refused_flags, reward_scores = [], [], [], []\n"
    "\n"
    "    for i, item in enumerate(questions):\n"
    "        question = item['question']\n"
    "        gold     = item.get('answer', '')\n"
    "        if isinstance(gold, list):\n"
    "            gold = gold[0] if gold else ''\n"
    "        gold   = str(gold) if gold is not None else ''\n"
    "        doc_id = Path(item['doc_id']).stem\n"
    "\n"
    "        graph  = load_graph(str(GRAPH_DIR), doc_id)\n"
    "        pf     = PARSED_DIR / f'{doc_id}.json'\n"
    "        parsed = json.loads(pf.read_text(encoding='utf-8')) if pf.exists() else None\n"
    "        route  = router.route(question)\n"
    "\n"
    "        text_pt   = EMB_DIR / f'{doc_id}_text.pt'\n"
    "        query_emb = (torch.load(text_pt, weights_only=True).mean(0)\n"
    "                     if text_pt.exists() else torch.zeros(256))\n"
    "\n"
    "        if graph and parsed and route in ('GRAPH', 'HYBRID'):\n"
    "            result = retriever.retrieve(query_emb, graph, parsed, [])\n"
    "        else:\n"
    "            vi    = faiss_indices.get(doc_id)\n"
    "            nodes = vi.search(query_emb, top_k=10) if vi and vi.index else []\n"
    "            result = {'nodes':nodes,'reward':0.5,'refused':False,\n"
    "                      'rounds':0,'reward_detail':{}}\n"
    "\n"
    "        prompt = build_prompt(\n"
    "            question, result['nodes'],\n"
    "            parsed or {'elements':[]},\n"
    "            result['reward_detail'], result['refused'],\n"
    "            benchmark='mmlongbench',\n"
    "        )\n"
    "        answer = vlm_eval.generate(prompt, temperature=0.0, max_tokens=256)\n"
    "\n"
    "        predictions.append(answer)\n"
    "        golds.append(gold)\n"
    "        refused_flags.append(result['refused'])\n"
    "        reward_scores.append(result['reward'])\n"
    "\n"
    "        if (i + 1) % 10 == 0:\n"
    "            print(f'  [{i+1}/{len(questions)}] route={route} '\n"
    "                  f'R={result[\"reward\"]:.2f} refused={result[\"refused\"]}')\n"
    "\n"
    "    is_answerable = [not r for r in refused_flags]\n"
    "    metrics = compute_all_metrics(predictions, golds, is_answerable, refused_flags)\n"
    "    return {\n"
    "        'n_questions':len(questions), 'metrics':metrics,\n"
    "        'predictions':predictions, 'golds':golds,\n"
    "        'reward_scores':reward_scores, 'refused_flags':refused_flags,\n"
    "    }\n"
    "\n"
    "print('run_gramm_rag_mmlb() defined.')"
))

cells.append(code(
    "gramm_results = {}\n"
    "\n"
    "for seed in [42, 123, 456]:\n"
    "    out_path = RESULTS_DIR / f'gramm_mmlongbench_s{seed}.json'\n"
    "    if out_path.exists():\n"
    "        print(f'Seed {seed}: results exist at {out_path}')\n"
    "        gramm_results[seed] = json.loads(out_path.read_text())\n"
    "        continue\n"
    "    print(f'\\n=== GraMM-RAG / seed={seed} ===')\n"
    "    res = run_gramm_rag_mmlb(pilot_questions, seed=seed)\n"
    "    gramm_results[seed] = res\n"
    "    out_path.write_text(json.dumps(res, indent=2))\n"
    "    m = res['metrics']\n"
    "    print(f'  ANLS={m[\"anls\"]:.3f}  F1={m[\"f1\"]:.3f}  Acc={m[\"accuracy\"]:.3f}  '\n"
    "          f'AbsF1={m.get(\"abstention_f1\",0):.3f}  '\n"
    "          f'Refused={sum(res[\"refused_flags\"])}/{res[\"n_questions\"]}')\n"
    "\n"
    "print('\\nAll seeds complete.')"
))

# ── Phase 10 ──────────────────────────────────────────────────────────────────
cells.append(md(
    "## Phase 10 — Results Comparison Table\n"
    "\n"
    "Aggregate GraMM-RAG results across 3 seeds and compare against the flat-vector RAG baseline."
))

cells.append(code(
    "import pandas as pd\n"
    "import numpy as np\n"
    "\n"
    "rows = []\n"
    "\n"
    "if vector_out_path.exists():\n"
    "    vr = json.loads(vector_out_path.read_text())\n"
    "    m  = vr['metrics']\n"
    "    rows.append({\n"
    "        'System': 'Flat-vector RAG',\n"
    "        'N': vr['n_questions'],\n"
    "        'ANLS': f\"{m['anls']:.3f}\",\n"
    "        'F1': f\"{m['f1']:.3f}\",\n"
    "        'Accuracy': f\"{m['accuracy']:.3f}\",\n"
    "        'Abstention-F1': f\"{m.get('abstention_f1',0):.3f}\",\n"
    "        'Refused': 0, 'Seed': '-',\n"
    "    })\n"
    "\n"
    "anls_vals, f1_vals, acc_vals = [], [], []\n"
    "for seed, res in sorted(gramm_results.items()):\n"
    "    m = res['metrics']\n"
    "    rows.append({\n"
    "        'System': 'GraMM-RAG',\n"
    "        'N': res['n_questions'],\n"
    "        'ANLS': f\"{m['anls']:.3f}\",\n"
    "        'F1': f\"{m['f1']:.3f}\",\n"
    "        'Accuracy': f\"{m['accuracy']:.3f}\",\n"
    "        'Abstention-F1': f\"{m.get('abstention_f1',0):.3f}\",\n"
    "        'Refused': sum(res['refused_flags']),\n"
    "        'Seed': seed,\n"
    "    })\n"
    "    anls_vals.append(m['anls'])\n"
    "    f1_vals.append(m['f1'])\n"
    "    acc_vals.append(m['accuracy'])\n"
    "\n"
    "if anls_vals:\n"
    "    rows.append({\n"
    "        'System': 'GraMM-RAG (mean±std)',\n"
    "        'N': len(pilot_questions),\n"
    "        'ANLS': f\"{np.mean(anls_vals):.3f}±{np.std(anls_vals):.3f}\",\n"
    "        'F1': f\"{np.mean(f1_vals):.3f}±{np.std(f1_vals):.3f}\",\n"
    "        'Accuracy': f\"{np.mean(acc_vals):.3f}±{np.std(acc_vals):.3f}\",\n"
    "        'Abstention-F1': '-', 'Refused': '-', 'Seed': 'mean',\n"
    "    })\n"
    "\n"
    "if rows:\n"
    "    df = pd.DataFrame(rows)\n"
    "    print('=== GraMM-RAG vs Flat-Vector RAG on MMLongBench-Doc (Full Run) ===')\n"
    "    print(f'N={len(pilot_questions)} questions, Seed={SEED}, Model=Qwen2.5-VL-72B-Instruct')\n"
    "    print()\n"
    "    print(df.to_string(index=False))\n"
    "else:\n"
    "    print('No results yet. Run Phases 8–9 first.')"
))

cells.append(code(
    "summary = {\n"
    "    'N_PILOT': N_PILOT, 'SEED': SEED,\n"
    "    'model': 'Qwen/Qwen2.5-VL-72B-Instruct',\n"
    "    'flat_vector_rag': json.loads(vector_out_path.read_text())['metrics']\n"
    "        if vector_out_path.exists() else None,\n"
    "    'gramm_rag': {str(s): r['metrics'] for s, r in gramm_results.items()},\n"
    "}\n"
    "(RESULTS_DIR / 'summary_mmlb.json').write_text(json.dumps(summary, indent=2))\n"
    "\n"
    "print('All results saved to results/')\n"
    "print()\n"
    "print('Estimated API cost: ~$22 (Qwen2.5-VL-72B × 3 seeds × 1,091 Qs @ ~$0.005/call)')"
))

# ─── Build notebook JSON ──────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbformat": 4,
            "version": "3.10.0"
        }
    },
    "cells": cells,
}

out = pathlib.Path(__file__).parent / "mmlongbench_e2e.ipynb"
out.write_text(json.dumps(notebook, indent=1, ensure_ascii=False), encoding="utf-8")
n_md   = sum(1 for c in cells if c["cell_type"] == "markdown")
n_code = sum(1 for c in cells if c["cell_type"] == "code")
print(f"Notebook written: {out}")
print(f"Total cells: {len(cells)} ({n_md} md + {n_code} code)")
